sonar.organization=victorcc02
sonar.projectKey=urjc-yosoytupadel-frontend
sonar.projectName=YoSoyTuPadel Frontend

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.jsx,src/**/*.spec.jsx,src/**/*.test.tsx,src/**/*.spec.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info