spring.application.name=backend

app.load-sample-data=true

# Conexion MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/yosoytupadel_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Madrid}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:pass}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

server.port=${SERVER_PORT:8443}

# Configuracion del certificado autofirmado
server.ssl.key-store=classpath:keystore.jks
server.ssl.key-store-password=password
server.ssl.key-password=secret

# ${.. --> Variables de entorno